// <auto-generated />
using System;
using Mayar.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mayar.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260405203151_AddHeroBgColorToContentPage")]
    partial class AddHeroBgColorToContentPage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Mayar.Api.Entities.About", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("HeroBgColor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("HeroSubtitleArabic")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("HeroSubtitleEnglish")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("HeroTitleArabic")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("HeroTitleEnglish")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MetaDescriptionArabic")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MetaDescriptionEnglish")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MetaTitleArabic")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MetaTitleEnglish")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MissionDescriptionArabic")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MissionDescriptionEnglish")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MissionIcon")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MissionTitleArabic")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MissionTitleEnglish")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("VisionDescriptionArabic")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("VisionDescriptionEnglish")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("VisionIcon")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("VisionTitleArabic")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("VisionTitleEnglish")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("WhoWeAreTitleArabic")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("WhoWeAreTitleEnglish")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("About");
                });

            modelBuilder.Entity("Mayar.Api.Entities.AboutContactItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AboutId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ActionValue")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LabelArabic")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LabelEnglish")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AboutId");

                    b.ToTable("AboutContactItems");
                });

            modelBuilder.Entity("Mayar.Api.Entities.AboutParagraph", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AboutId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ContentArabic")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ContentEnglish")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AboutId");

                    b.ToTable("AboutParagraphs");
                });

            modelBuilder.Entity("Mayar.Api.Entities.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Block")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Building")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext");

                    b.Property<string>("FlatOffice")
                        .HasColumnType("longtext");

                    b.Property<string>("Floor")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("Mayar.Api.Entities.BottomCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<long?>("DisplayOrder")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("MiddleCategoryId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Slug")
                        .HasColumnType("longtext");

                    b.Property<string>("TitleArabic")
                        .HasColumnType("longtext");

                    b.Property<string>("TitleEnglish")
                        .HasColumnType("longtext");

                    b.Property<Guid>("TopCategoryId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("MiddleCategoryId");

                    b.ToTable("BottomCategories");
                });

            modelBuilder.Entity("Mayar.Api.Entities.CartItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid?>("ProductColorId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ProductSizeId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("SessionId")
                        .HasColumnType("longtext");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ProductColorId");

                    b.HasIndex("ProductId");

                    b.HasIndex("ProductSizeId");

                    b.HasIndex("UserId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("Mayar.Api.Entities.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("HeroBgColor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("HeroHeadingAr")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("HeroHeadingEn")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("HeroSubheadingAr")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("HeroSubheadingEn")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MapEmbedUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("MapHeight")
                        .HasColumnType("int");

                    b.Property<string>("MetaDescriptionAr")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MetaDescriptionEn")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MetaTitleAr")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MetaTitleEn")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("ShowMap")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Contact");
                });

            modelBuilder.Entity("Mayar.Api.Entities.ContactCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ContactId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LabelAr")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LabelEn")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("ValueAr")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ValueEn")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ContactId");

                    b.ToTable("ContactCards");
                });

            modelBuilder.Entity("Mayar.Api.Entities.ContentPage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ContactEmail")
                        .HasColumnType("longtext");

                    b.Property<string>("ContactNoteAr")
                        .HasColumnType("longtext");

                    b.Property<string>("ContactNoteEn")
                        .HasColumnType("longtext");

                    b.Property<string>("ContactPhone")
                        .HasColumnType("longtext");

                    b.Property<string>("ContactTitleAr")
                        .HasColumnType("longtext");

                    b.Property<string>("ContactTitleEn")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("EffectiveDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("HeroBgColor")
                        .HasColumnType("longtext");

                    b.Property<string>("IntroAr")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("IntroEn")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastRevisedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("MetaDescriptionAr")
                        .HasColumnType("longtext");

                    b.Property<string>("MetaDescriptionEn")
                        .HasColumnType("longtext");

                    b.Property<string>("MetaTitleAr")
                        .HasColumnType("longtext");

                    b.Property<string>("MetaTitleEn")
                        .HasColumnType("longtext");

                    b.Property<string>("PageType")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TitleAr")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TitleEn")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("PageType")
                        .IsUnique();

                    b.ToTable("ContentPages");
                });

            modelBuilder.Entity("Mayar.Api.Entities.ContentSection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("BodyAr")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("BodyEn")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("ContentPageId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("TitleAr")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TitleEn")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ContentPageId");

                    b.ToTable("ContentSections");
                });

            modelBuilder.Entity("Mayar.Api.Entities.CouponCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Code")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("DiscountAmountINR")
                        .HasColumnType("decimal(18,0)");

                    b.Property<decimal>("DiscountAmountKWD")
                        .HasColumnType("decimal(18,3)");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("CouponCodes");
                });

            modelBuilder.Entity("Mayar.Api.Entities.HeroSlide", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AltText")
                        .HasColumnType("longtext");

                    b.Property<string>("BannerName")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CtaTextArabic")
                        .HasColumnType("longtext");

                    b.Property<string>("CtaTextEnglish")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("CurrentPriceINR")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CurrentPriceKWD")
                        .HasColumnType("decimal(18,3)");

                    b.Property<string>("CustomUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("DescriptionArabic")
                        .HasColumnType("longtext");

                    b.Property<string>("DescriptionEnglish")
                        .HasColumnType("longtext");

                    b.Property<string>("DesktopImageUrl")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LabelArabic")
                        .HasColumnType("longtext");

                    b.Property<string>("LabelEnglish")
                        .HasColumnType("longtext");

                    b.Property<string>("LinkType")
                        .HasColumnType("longtext");

                    b.Property<string>("MobileImageUrl")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("OldPriceINR")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("OldPriceKWD")
                        .HasColumnType("decimal(18,3)");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ProductTypeId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Slug")
                        .HasColumnType("longtext");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<Guid?>("SubcategoryId")
                        .HasColumnType("char(36)");

                    b.Property<string>("TitleArabic")
                        .HasColumnType("longtext");

                    b.Property<string>("TitleEnglish")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ProductId");

                    b.HasIndex("ProductTypeId");

                    b.HasIndex("SubcategoryId");

                    b.ToTable("HeroSlides");
                });

            modelBuilder.Entity("Mayar.Api.Entities.MiddleCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ButtonLink")
                        .HasColumnType("longtext");

                    b.Property<string>("ButtonTextArabic")
                        .HasColumnType("longtext");

                    b.Property<string>("ButtonTextEnglish")
                        .HasColumnType("longtext");

                    b.Property<long?>("DisplayOrder")
                        .HasColumnType("bigint");

                    b.Property<string>("ImageAlt")
                        .HasColumnType("longtext");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Slug")
                        .HasColumnType("longtext");

                    b.Property<string>("SubtitleArabic")
                        .HasColumnType("longtext");

                    b.Property<string>("SubtitleEnglish")
                        .HasColumnType("longtext");

                    b.Property<string>("TitleArabic")
                        .HasColumnType("longtext");

                    b.Property<string>("TitleEnglish")
                        .HasColumnType("longtext");

                    b.Property<Guid>("TopCategoryId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("TopCategoryId");

                    b.ToTable("MiddleCategories");
                });

            modelBuilder.Entity("Mayar.Api.Entities.NewsLetter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("SubscribedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("NewsLetters");
                });

            modelBuilder.Entity("Mayar.Api.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CouponCodeId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Currency")
                        .HasColumnType("longtext");

                    b.Property<string>("CustomerEmail")
                        .HasColumnType("longtext");

                    b.Property<string>("CustomerFirstName")
                        .HasColumnType("longtext");

                    b.Property<string>("CustomerLastName")
                        .HasColumnType("longtext");

                    b.Property<string>("CustomerPhone")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("DiscountAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<string>("OrderNumber")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("int");

                    b.Property<string>("PromoCode")
                        .HasColumnType("longtext");

                    b.Property<string>("SessionId")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ShippedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("ShippingAddressId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ShippingArea")
                        .HasColumnType("longtext");

                    b.Property<string>("ShippingBlock")
                        .HasColumnType("longtext");

                    b.Property<string>("ShippingBuilding")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("ShippingCost")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("ShippingEstimateAr")
                        .HasColumnType("longtext");

                    b.Property<string>("ShippingEstimateEn")
                        .HasColumnType("longtext");

                    b.Property<string>("ShippingFlatOffice")
                        .HasColumnType("longtext");

                    b.Property<string>("ShippingFloor")
                        .HasColumnType("longtext");

                    b.Property<string>("ShippingMethodId")
                        .HasColumnType("longtext");

                    b.Property<string>("ShippingMethodNameAr")
                        .HasColumnType("longtext");

                    b.Property<string>("ShippingMethodNameEn")
                        .HasColumnType("longtext");

                    b.Property<string>("ShippingNotes")
                        .HasColumnType("longtext");

                    b.Property<string>("ShippingStreet")
                        .HasColumnType("longtext");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal?>("SubTotal")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("TaxAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("TotalAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("TrackingId")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("CouponCodeId");

                    b.HasIndex("OrderNumber")
                        .IsUnique();

                    b.HasIndex("ShippingAddressId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Mayar.Api.Entities.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal?>("DiscountAmount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ProductColor")
                        .HasColumnType("longtext");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ProductImageUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("ProductNameArabic")
                        .HasColumnType("longtext");

                    b.Property<string>("ProductNameEnglish")
                        .HasColumnType("longtext");

                    b.Property<string>("ProductSize")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("ProductVariantId")
                        .HasColumnType("char(36)");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal?>("TotalPrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("UnitPrice")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.HasIndex("ProductVariantId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("Mayar.Api.Entities.OrderStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ChangedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("FromStatus")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasColumnType("longtext");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("char(36)");

                    b.Property<int?>("ToStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChangedBy");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderStatusHistory");
                });

            modelBuilder.Entity("Mayar.Api.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CallbackResponse")
                        .HasColumnType("json");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CurrencyIso")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("ErrorResponse")
                        .HasColumnType("json");

                    b.Property<string>("GatewayEnvironment")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("GatewayResponse")
                        .HasColumnType("json");

                    b.Property<decimal>("InvoiceAmount")
                        .HasColumnType("decimal(18,3)");

                    b.Property<string>("InvoiceId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("char(36)");

                    b.Property<string>("PaymentGateway")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PaymentId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PaymentMethodId")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("SessionId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("TransactionReference")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId")
                        .IsUnique();

                    b.HasIndex("OrderId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Mayar.Api.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal?>("BasePriceINR")
                        .HasColumnType("decimal(18,0)");

                    b.Property<decimal?>("BasePriceKWD")
                        .HasColumnType("decimal(18,3)");

                    b.Property<Guid?>("BottomCategoryId")
                        .HasColumnType("char(36)");

                    b.Property<string>("BrandArabic")
                        .HasColumnType("longtext");

                    b.Property<string>("BrandEnglish")
                        .HasColumnType("longtext");

                    b.Property<string>("CanonicalUrl")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("CompareAtPriceINR")
                        .HasColumnType("decimal(18,0)");

                    b.Property<decimal?>("CompareAtPriceKWD")
                        .HasColumnType("decimal(18,3)");

                    b.Property<string>("FullDescriptionArabic")
                        .HasColumnType("longtext");

                    b.Property<string>("FullDescriptionEnglish")
                        .HasColumnType("longtext");

                    b.Property<bool>("InStock")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("IsBestSeller")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("IsFeatured")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsNew")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool?>("IsOnSale")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("MetaDescription")
                        .HasColumnType("longtext");

                    b.Property<string>("MetaKeywords")
                        .HasColumnType("longtext");

                    b.Property<string>("MetaTitle")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("MiddleCategoryId")
                        .HasColumnType("char(36)");

                    b.Property<string>("NameArabic")
                        .HasColumnType("longtext");

                    b.Property<string>("NameEnglish")
                        .HasColumnType("longtext");

                    b.Property<string>("OGDescription")
                        .HasColumnType("longtext");

                    b.Property<string>("OGImageUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("OGTitle")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("Rating")
                        .HasColumnType("decimal(18,1)");

                    b.Property<string>("ReturnInfoArabic")
                        .HasColumnType("longtext");

                    b.Property<string>("ReturnInfoEnglish")
                        .HasColumnType("longtext");

                    b.Property<int?>("ReviewCount")
                        .HasColumnType("int");

                    b.Property<string>("ShippingInfoArabic")
                        .HasColumnType("longtext");

                    b.Property<string>("ShippingInfoEnglish")
                        .HasColumnType("longtext");

                    b.Property<string>("ShortDescriptionArabic")
                        .HasColumnType("longtext");

                    b.Property<string>("ShortDescriptionEnglish")
                        .HasColumnType("longtext");

                    b.Property<string>("Slug")
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.Property<Guid>("TopCategoryId")
                        .HasColumnType("char(36)");

                    b.Property<string>("TwitterDescription")
                        .HasColumnType("longtext");

                    b.Property<string>("TwitterTitle")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Mayar.Api.Entities.ProductCareInstruction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("InstructionArabic")
                        .HasColumnType("longtext");

                    b.Property<string>("InstructionEnglish")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductCareInstructions");
                });

            modelBuilder.Entity("Mayar.Api.Entities.ProductColor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Hex")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("NameArabic")
                        .HasColumnType("longtext");

                    b.Property<string>("NameEnglish")
                        .HasColumnType("longtext");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductColors");
                });

            modelBuilder.Entity("Mayar.Api.Entities.ProductFeature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("IconName")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LabelArabic")
                        .HasColumnType("longtext");

                    b.Property<string>("LabelEnglish")
                        .HasColumnType("longtext");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductFeatures");
                });

            modelBuilder.Entity("Mayar.Api.Entities.ProductImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ImageAlt")
                        .HasColumnType("longtext");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");
                });

            modelBuilder.Entity("Mayar.Api.Entities.ProductSize", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Label")
                        .HasColumnType("longtext");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductSizes");
                });

            modelBuilder.Entity("Mayar.Api.Entities.ProductSpecification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LabelArabic")
                        .HasColumnType("longtext");

                    b.Property<string>("LabelEnglish")
                        .HasColumnType("longtext");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ValueArabic")
                        .HasColumnType("longtext");

                    b.Property<string>("ValueEnglish")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductSpecifications");
                });

            modelBuilder.Entity("Mayar.Api.Entities.ProductVariant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal?>("BasePriceINR")
                        .HasColumnType("decimal(18,0)");

                    b.Property<decimal?>("BasePriceKWD")
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal?>("CompareAtPriceINR")
                        .HasColumnType("decimal(18,0)");

                    b.Property<decimal?>("CompareAtPriceKWD")
                        .HasColumnType("decimal(18,3)");

                    b.Property<bool>("InStock")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("ProductColorId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ProductSizeId")
                        .HasColumnType("char(36)");

                    b.Property<int?>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductColorId");

                    b.HasIndex("ProductSizeId");

                    b.HasIndex("ProductId", "ProductColorId", "ProductSizeId")
                        .IsUnique();

                    b.ToTable("ProductVariants");
                });

            modelBuilder.Entity("Mayar.Api.Entities.PromoBanner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AltText")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CtaTextArabic")
                        .HasColumnType("longtext");

                    b.Property<string>("CtaTextEnglish")
                        .HasColumnType("longtext");

                    b.Property<string>("CustomUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("DesktopImageUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("InternalName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LabelArabic")
                        .HasColumnType("longtext");

                    b.Property<string>("LabelEnglish")
                        .HasColumnType("longtext");

                    b.Property<string>("LayoutType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LinkType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MobileImageUrl")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ProductTypeId")
                        .HasColumnType("char(36)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<Guid?>("SubcategoryId")
                        .HasColumnType("char(36)");

                    b.Property<string>("TitleArabic")
                        .HasColumnType("longtext");

                    b.Property<string>("TitleEnglish")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ProductId");

                    b.HasIndex("ProductTypeId");

                    b.HasIndex("SubcategoryId");

                    b.ToTable("PromoBanners");
                });

            modelBuilder.Entity("Mayar.Api.Entities.RecentlyViewed", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("ViewedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("RecentlyViewedProducts");
                });

            modelBuilder.Entity("Mayar.Api.Entities.TopCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("BadgeArabic")
                        .HasColumnType("longtext");

                    b.Property<string>("BadgeEnglish")
                        .HasColumnType("longtext");

                    b.Property<long?>("DisplayOrder")
                        .HasColumnType("bigint");

                    b.Property<string>("ImageAlt")
                        .HasColumnType("longtext");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Slug")
                        .HasColumnType("longtext");

                    b.Property<string>("TitleArabic")
                        .HasColumnType("longtext");

                    b.Property<string>("TitleEnglish")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("TopCategories");
                });

            modelBuilder.Entity("Mayar.Api.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("GatewayResponse")
                        .HasColumnType("longtext");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("char(36)");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TransactionNumber")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("Mayar.Api.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<string>("Country")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<string>("PinCode")
                        .HasColumnType("longtext");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("250d8861-ab70-47b8-b916-d1ff82c61c41"),
                            Email = "admin@mayar.com",
                            Name = "Admin",
                            PasswordHash = "$2a$11$TlVTzoceis6pxV/pKAa02efM.6HT6mlZ/M/lm6wduQuI4fOsQaJum",
                            Role = "Admin"
                        });
                });

            modelBuilder.Entity("Mayar.Api.Entities.Wishlist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Brand")
                        .HasColumnType("longtext");

                    b.Property<string>("ColorHex")
                        .HasColumnType("longtext");

                    b.Property<string>("ColorNameArabic")
                        .HasColumnType("longtext");

                    b.Property<string>("ColorNameEnglish")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("CompareAtPriceINR")
                        .HasColumnType("decimal(18,0)");

                    b.Property<decimal?>("CompareAtPriceKWD")
                        .HasColumnType("decimal(18,3)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("PriceINR")
                        .HasColumnType("decimal(18,0)");

                    b.Property<decimal?>("PriceKWD")
                        .HasColumnType("decimal(18,3)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ProductNameArabic")
                        .HasColumnType("longtext");

                    b.Property<string>("ProductNameEnglish")
                        .HasColumnType("longtext");

                    b.Property<string>("ProductSlug")
                        .HasColumnType("longtext");

                    b.Property<Guid>("ProductVariantId")
                        .HasColumnType("char(36)");

                    b.Property<string>("SizeLabel")
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ProductVariantId");

                    b.HasIndex("UserId", "ProductVariantId")
                        .IsUnique();

                    b.ToTable("Wishlists");
                });

            modelBuilder.Entity("Mayar.Api.Entities.AboutContactItem", b =>
                {
                    b.HasOne("Mayar.Api.Entities.About", "About")
                        .WithMany("ContactItems")
                        .HasForeignKey("AboutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("About");
                });

            modelBuilder.Entity("Mayar.Api.Entities.AboutParagraph", b =>
                {
                    b.HasOne("Mayar.Api.Entities.About", "About")
                        .WithMany("Paragraphs")
                        .HasForeignKey("AboutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("About");
                });

            modelBuilder.Entity("Mayar.Api.Entities.Address", b =>
                {
                    b.HasOne("Mayar.Api.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Mayar.Api.Entities.BottomCategory", b =>
                {
                    b.HasOne("Mayar.Api.Entities.MiddleCategory", "MiddleCategory")
                        .WithMany("BottomCategories")
                        .HasForeignKey("MiddleCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MiddleCategory");
                });

            modelBuilder.Entity("Mayar.Api.Entities.CartItem", b =>
                {
                    b.HasOne("Mayar.Api.Entities.ProductColor", "ProductColor")
                        .WithMany()
                        .HasForeignKey("ProductColorId");

                    b.HasOne("Mayar.Api.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mayar.Api.Entities.ProductSize", "ProductSize")
                        .WithMany()
                        .HasForeignKey("ProductSizeId");

                    b.HasOne("Mayar.Api.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Product");

                    b.Navigation("ProductColor");

                    b.Navigation("ProductSize");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Mayar.Api.Entities.ContactCard", b =>
                {
                    b.HasOne("Mayar.Api.Entities.Contact", "Contact")
                        .WithMany("ContactCards")
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contact");
                });

            modelBuilder.Entity("Mayar.Api.Entities.ContentSection", b =>
                {
                    b.HasOne("Mayar.Api.Entities.ContentPage", "ContentPage")
                        .WithMany("Sections")
                        .HasForeignKey("ContentPageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContentPage");
                });

            modelBuilder.Entity("Mayar.Api.Entities.HeroSlide", b =>
                {
                    b.HasOne("Mayar.Api.Entities.TopCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.HasOne("Mayar.Api.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");

                    b.HasOne("Mayar.Api.Entities.BottomCategory", "ProductType")
                        .WithMany()
                        .HasForeignKey("ProductTypeId");

                    b.HasOne("Mayar.Api.Entities.MiddleCategory", "Subcategory")
                        .WithMany()
                        .HasForeignKey("SubcategoryId");

                    b.Navigation("Category");

                    b.Navigation("Product");

                    b.Navigation("ProductType");

                    b.Navigation("Subcategory");
                });

            modelBuilder.Entity("Mayar.Api.Entities.MiddleCategory", b =>
                {
                    b.HasOne("Mayar.Api.Entities.TopCategory", "TopCategory")
                        .WithMany("MiddleCategories")
                        .HasForeignKey("TopCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TopCategory");
                });

            modelBuilder.Entity("Mayar.Api.Entities.NewsLetter", b =>
                {
                    b.HasOne("Mayar.Api.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Mayar.Api.Entities.Order", b =>
                {
                    b.HasOne("Mayar.Api.Entities.CouponCode", "CouponCode")
                        .WithMany()
                        .HasForeignKey("CouponCodeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Mayar.Api.Entities.Address", "ShippingAddress")
                        .WithMany()
                        .HasForeignKey("ShippingAddressId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Mayar.Api.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CouponCode");

                    b.Navigation("ShippingAddress");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Mayar.Api.Entities.OrderItem", b =>
                {
                    b.HasOne("Mayar.Api.Entities.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mayar.Api.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Mayar.Api.Entities.ProductVariant", "ProductVariant")
                        .WithMany()
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Order");

                    b.Navigation("Product");

                    b.Navigation("ProductVariant");
                });

            modelBuilder.Entity("Mayar.Api.Entities.OrderStatusHistory", b =>
                {
                    b.HasOne("Mayar.Api.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("ChangedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Mayar.Api.Entities.Order", "Order")
                        .WithMany("StatusHistory")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Mayar.Api.Entities.Payment", b =>
                {
                    b.HasOne("Mayar.Api.Entities.Order", "Order")
                        .WithMany("Payments")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Mayar.Api.Entities.ProductCareInstruction", b =>
                {
                    b.HasOne("Mayar.Api.Entities.Product", "Product")
                        .WithMany("CareInstructions")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Mayar.Api.Entities.ProductColor", b =>
                {
                    b.HasOne("Mayar.Api.Entities.Product", "Product")
                        .WithMany("Colors")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Mayar.Api.Entities.ProductFeature", b =>
                {
                    b.HasOne("Mayar.Api.Entities.Product", "Product")
                        .WithMany("Features")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Mayar.Api.Entities.ProductImage", b =>
                {
                    b.HasOne("Mayar.Api.Entities.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Mayar.Api.Entities.ProductSize", b =>
                {
                    b.HasOne("Mayar.Api.Entities.Product", "Product")
                        .WithMany("Sizes")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Mayar.Api.Entities.ProductSpecification", b =>
                {
                    b.HasOne("Mayar.Api.Entities.Product", "Product")
                        .WithMany("Specifications")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Mayar.Api.Entities.ProductVariant", b =>
                {
                    b.HasOne("Mayar.Api.Entities.ProductColor", "ProductColor")
                        .WithMany()
                        .HasForeignKey("ProductColorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Mayar.Api.Entities.Product", "Product")
                        .WithMany("Variants")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mayar.Api.Entities.ProductSize", "ProductSize")
                        .WithMany()
                        .HasForeignKey("ProductSizeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("ProductColor");

                    b.Navigation("ProductSize");
                });

            modelBuilder.Entity("Mayar.Api.Entities.PromoBanner", b =>
                {
                    b.HasOne("Mayar.Api.Entities.TopCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Mayar.Api.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Mayar.Api.Entities.BottomCategory", "ProductType")
                        .WithMany()
                        .HasForeignKey("ProductTypeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Mayar.Api.Entities.MiddleCategory", "Subcategory")
                        .WithMany()
                        .HasForeignKey("SubcategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");

                    b.Navigation("Product");

                    b.Navigation("ProductType");

                    b.Navigation("Subcategory");
                });

            modelBuilder.Entity("Mayar.Api.Entities.Transaction", b =>
                {
                    b.HasOne("Mayar.Api.Entities.Order", "Order")
                        .WithMany("Transactions")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Mayar.Api.Entities.Wishlist", b =>
                {
                    b.HasOne("Mayar.Api.Entities.ProductVariant", "ProductVariant")
                        .WithMany()
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductVariant");
                });

            modelBuilder.Entity("Mayar.Api.Entities.About", b =>
                {
                    b.Navigation("ContactItems");

                    b.Navigation("Paragraphs");
                });

            modelBuilder.Entity("Mayar.Api.Entities.Contact", b =>
                {
                    b.Navigation("ContactCards");
                });

            modelBuilder.Entity("Mayar.Api.Entities.ContentPage", b =>
                {
                    b.Navigation("Sections");
                });

            modelBuilder.Entity("Mayar.Api.Entities.MiddleCategory", b =>
                {
                    b.Navigation("BottomCategories");
                });

            modelBuilder.Entity("Mayar.Api.Entities.Order", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("Payments");

                    b.Navigation("StatusHistory");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Mayar.Api.Entities.Product", b =>
                {
                    b.Navigation("CareInstructions");

                    b.Navigation("Colors");

                    b.Navigation("Features");

                    b.Navigation("Images");

                    b.Navigation("Sizes");

                    b.Navigation("Specifications");

                    b.Navigation("Variants");
                });

            modelBuilder.Entity("Mayar.Api.Entities.TopCategory", b =>
                {
                    b.Navigation("MiddleCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
